CREATE TABLE IF NOT EXISTS PluginFiles (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Path TEXT NOT NULL,
	NETType TEXT NOT NULL,
	PluginType TEXT NOT NULL,
	Name TEXT NULL,
	Description TEXT NULL,
	Enable INT NOT NULL DEFAULT 1,
	UNIQUE (Path, NETType)
);

CREATE TABLE IF NOT EXISTS PluginFactorys (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Plugin INTEGER NOT NULL,
	NETType TEXT NOT NULL,
	Autorun INTEGER NOT NULL DEFAULT 0,
	Enabled INTEGER NOT NULL DEFAULT 1,
	FOREIGN KEY (Plugin) REFERENCES PluginFiles(Id),
	UNIQUE (Plugin, NETType)
);